authentication/urls.py
from django.urls import path
from authentication.views import login, logout

app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

main/urls.py
from django.urls import path
from main.views import (show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id, register, 
                        login_user, logout_user, edit_item, delete_item, get_item_json, add_item_ajax, create_item_flutter)

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('delete/<int:id>', delete_item, name='delete_item'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-ajax/', add_item_ajax, name='add_item_ajax'),
    path('create-flutter/', create_item_flutter, name='create_item_flutter'),
]

snakeInventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

authentication/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    morph = models.CharField(max_length=255)
    price = models.IntegerField()
    amount = models.IntegerField()
    description = models.TextField()
    date_added = models.DateField(auto_now_add=True)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "morph", "price", "amount", "description"]

authentication/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login as auth_login
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout as auth_logout

@csrf_exempt
def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            # Status login sukses.
            return JsonResponse({
                "username": user.username,
                "status": True,
                "message": "Login sukses!"
                # Tambahkan data lainnya jika ingin mengirim data ke Flutter.
            }, status=200)
        else:
            return JsonResponse({
                "status": False,
                "message": "Login gagal, akun dinonaktifkan."
            }, status=401)

    else:
        return JsonResponse({
            "status": False,
            "message": "Login gagal, periksa kembali email atau kata sandi."
        }, status=401)
    
@csrf_exempt
def logout(request):
    username = request.user.username

    try:
        auth_logout(request)
        return JsonResponse({
            "username": username,
            "status": True,
            "message": "Logout berhasil!"
        }, status=200)
    except:
        return JsonResponse({
        "status": False,
        "message": "Logout gagal."
        }, status=401)

main/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from main.forms import ItemForm
from django.urls import reverse
from main.models import Item
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'class': 'PBP D',
        'items': items,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "main.html", context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_item(request, id):
    item = Item.objects.get(pk = id)

    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_item.html", context)

def delete_item(request, id):
    item = Item.objects.get(pk = id)
    item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def get_item_json(request):
    item_snake = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', item_snake))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        morph = request.POST.get("morph")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_item = Item(name=name, morph=morph, price=price, amount=amount, description=description, user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Snake for Adoption</h1>

<style>
    .button-style {
        display: flex;
        padding: 16px 28px;
        justify-content: center;
        align-items: center;
        gap: 8px;
        border-radius: 16px;
        border: none;
        background: #54BF21;
        color: #FFF;
        font-size: 16px;
        font-style: normal;
        font-weight: 400;
        line-height: normal;
    }
    a {
        text-decoration: none;
    }
</style>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input class="button-style" type="submit" value="Add Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_item.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<style>
    .button-style {
        display: flex;
        padding: 16px 28px;
        justify-content: center;
        align-items: center;
        gap: 8px;
        border-radius: 16px;
        border: none;
        background: #54BF21;
        color: #FFF;
        font-size: 16px;
        font-style: normal;
        font-weight: 400;
        line-height: normal;
    }
    a {
        text-decoration: none;
    }
</style>

<h1>Edit Item</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input class="button-style" type="submit" value="Edit Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Crimson+Text:wght@700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=family=Open+Sans:wght@400;500;600&display=swap" rel="stylesheet">

<style>
    body {
        background-image: url('https://e1.pxfuel.com/desktop-wallpaper/48/879/desktop-wallpaper-green-python-green-snake-tree-branch-reptile-coiled-snake-animals-green-tree-python.jpg');
        /* background-image: url('https://www.worldatlas.com/upload/a4/91/91/shutterstock-1708408498.jpg'); */
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        font-family: 'Open Sans', sans-serif;
        /* background-color: #060F02; */
    }

    .login {
        text-align: center; /* Center align the content */
        padding: 20px; /* Add padding to center align the content vertically */
    }

    td, h1, ul, li, p {
        color: #FDFFFB;
    }

    h1 {
        margin-top: 28px;
        text-align: center;
        font-family: 'Crimson Text', serif;
        font-size: 52px;
    }

    p {
        margin-top: 12px;
        margin-bottom: 0;
        font-weight: 500;
    }

    td {
        padding-bottom: 20px;
    }

    .label-container {
        width: 520px;
        background-color: rgba(255,255,255,0.13);
        border-radius: 10px;
        backdrop-filter: blur(10px);
        border: 2px solid rgba(255,255,255,0.1);
        box-shadow: 0 0 40px rgba(8,7,16,0.6);
        margin: 0 auto; /* Center align the container */
        padding: 20px; /* Add padding to center align the content horizontally */
        margin-top: 32px;
        padding-bottom: 48px;
    }

    .label-container1 {
        width: 360px;
        background-color: rgba(255,255,255,0.13);
        border-radius: 10px;
        backdrop-filter: blur(10px);
        border: 2px solid rgba(255,255,255,0.1);
        box-shadow: 0 0 40px rgba(8,7,16,0.6);
        margin: 0 auto; /* Center align the container */
        padding: 20px; /* Add padding to center align the content horizontally */
        margin-top: 32px;
    }

    .label-container2 {
        width: 360px;
        background-color: rgba(255,255,255,0.13);
        border-radius: 10px;
        backdrop-filter: blur(10px);
        border: 2px solid rgba(255,255,255,0.1);
        box-shadow: 0 0 40px rgba(8,7,16,0.6);
        margin: 0 auto; /* Center align the container */
        padding: 20px; /* Add padding to center align the content horizontally */
        margin-top: 16px;
    }

    .button-primary {
        padding: 16px 40px;
        display: inline-block;
        justify-content: center;
        align-items: center;
        gap: 8px;
        border-radius: 16px;
        border: none;
        background: #54BF21;
        color: #FFF;
        font-size: 16px;
        font-style: normal;
        font-weight: 400;
        line-height: normal;
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .button-secondary {
        padding: 16px 40px;
        display: inline-block;
        justify-content: center;
        align-items: center;
        gap: 8px;
        border-radius: 16px;
        border: none;
        background: #B1E09B;
        color: #060F02;
        font-size: 16px;
        font-style: normal;
        font-weight: 400;
        line-height: normal;
        margin-top: 16px;
    }

    a {
        text-decoration: none;
        margin-bottom: 0px;
    }
</style>

<div class = "login label-container">

    <h1>Login</h1>
    <div>
        <form method="POST" action="">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username" class="form-control label-container1">
            <input type="password" name="password" placeholder="Password" class="form-control label-container2">
            <input class="button-primary" type="submit" value="Login">
        </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        <p>Don't have an account yet?</p> <a href="{% url 'main:register' %}">Register Now</a>
    </div>

</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">

    <style>
        body {
            /* background-color: #FDFFFB; */
            background-image: url('https://e1.pxfuel.com/desktop-wallpaper/48/879/desktop-wallpaper-green-python-green-snake-tree-branch-reptile-coiled-snake-animals-green-tree-python.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            font-family: 'Open Sans', sans-serif;
        }

        table, th, td, h1 {
            margin-left: 20px;
            margin-right: 20px;
        }

        h5, p {
            margin-left: 12px;
            margin-right: 12px;
        }

        table, th, td {
            width: 100%;
            border: 2px solid rgba(255,255,255,0.1);
            border-collapse: collapse;
            padding: 16px;

        }

        label, td, h1, h5, p {
            color: #FDFFFB;
        }

        table {
            width: 1360px;
            background-color: rgba(255,255,255,0.13);
            top: 50%;
            left: 50%;
            border-radius: 10px;
            backdrop-filter: blur(10px);
            border: 2px solid rgba(255,255,255,0.1);
            box-shadow: 0 0 40px rgba(8,7,16,0.6);
            padding-left: 20px;
            padding-right: 20px;
        }

        .label-container {
            width: 360px;
            background-color: rgba(255,255,255,0.13);
            border-radius: 10px;
            backdrop-filter: blur(10px);
            border: 2px solid rgba(255,255,255,0.1);
            box-shadow: 0 0 40px rgba(8,7,16,0.6);
            margin-bottom: 20px;
            margin-left: 20px;
        }

        th {
            background-color: #54BF21;
            color: #FFF;
        }

        h1 {
            padding-top: 12px;
            text-align: center;
            font-family: 'Crimson Text', serif;
            font-size: 64px;
            color: #FDFFFB;
        }

        h5 {
            padding-top: 21px;
            font-family: 'Crimson Text', serif;
            font-size: 24px;
            color: #FDFFFB;
        }

        h6 {
            padding-top: 20px;
            font-family: 'Open Sans', sans-serif;
            font-size: 16px;
            color: #FDFFFB;
            margin-left: 20px;
        }

        h5, p {
            padding-left: 20px;
        }

        th:nth-child(1) {
            border-radius: 10px 0 0 0;
        }

        th:nth-child(7) {
            border-radius: 0 10px 0 0;
        }

        td:nth-child(1) {
            border-radius: 0 0 0 10px;
        }

        td:nth-child(7) {
            border-radius: 0 0 10px 0;
        }

         /* Set the percentage widths for each column */
        th:nth-child(1), td:nth-child(1) {
            width: 15%;
        }

        th:nth-child(2), td:nth-child(2) {
            width: 20%;
        }

        th:nth-child(3), td:nth-child(3) {
            width: 10%;
            text-align: center;
        }

        th:nth-child(4), td:nth-child(4) {
            width: 5%;
            text-align: center;
        }

        th:nth-child(5), td:nth-child(5) {
            width: 32%;
        }

        th:nth-child(6), td:nth-child(6) {
            width: 12%;
            text-align: center;
        }

        th:nth-child(6), td:nth-child(7) {
            width: 8%;
            text-align: center;
            align-items: center;
        }

        .button-primary {
            display: flex;
            padding: 16px 28px;
            justify-content: center;
            align-items: center;
            gap: 8px;
            border-radius: 16px;
            border: none;
            background: #54BF21;
            color: #FFF;
            font-size: 16px;
            font-style: normal;
            font-weight: 400;
            line-height: normal;
            margin-bottom: 20px;
            margin-left: 20px;
        }

        a {
            text-decoration: none;
        }

        a[href="{% url 'main:logout' %}"] .button-primary {
            background: #AF2323;
            margin-bottom: 0px;
        }
        
        .button-secondary {
            display: flex;
            padding: 12px 20px;
            justify-content: center;
            align-items: center;
            gap: 8px;
            border-radius: 12px;
            border: 2px solid #54BF21;
            background: none;
            color: #FFF;
            font-size: 12px;
            font-style: normal;
            font-weight: 400;
            line-height: normal;
            margin-bottom: 20px;
        }

        .button-secondary2 {
            display: flex;
            padding: 16px 28px;
            justify-content: center;
            align-items: center;
            gap: 8px;
            border-radius: 12px;
            border: 2px solid #54BF21;
            background: none;
            color: #FFF;
            font-size: 16px;
            font-style: normal;
            font-weight: 400;
            line-height: normal;
            margin-bottom: 20px;
        }

        .button-secondary.delete-button {
            display: flex;
            padding: 12px 20px;
            justify-content: center;
            align-items: center;
            gap: 8px;
            border-radius: 12px;
            border: 2px solid #AF2323;
            background: none;
            color: #FFF;
            font-size: 12px;
            font-style: normal;
            font-weight: 400;
            line-height: normal;
            margin-bottom: 0;
        }
        
        .navbar {
            background-color: #060F02;
            width: 100%;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 20px;
            color: #FFF;
        }

        .logo {
            font-size: 24px;
            font-weight: bold;

        }

        .nav-links {
            display: flex;
            gap: 20px;
        }

        .nav-links a {
            text-decoration: none;
            color: #FFF;
        }
    </style>

    <div class="navbar">
        <div class="logo">
            <img src="https://user-images.githubusercontent.com/119391657/272463956-10e10be9-7aa5-4653-b77f-71bedd6eb6e5.png" alt="Logo">

        </div>
        <div class="nav-links">
            <a href="#">Home</a>
        </div>
        <a href="{% url 'main:logout' %}">
            <button class="button-primary">
                Logout
            </button>
        </a>
    </div>

    <h1>Serpent's Haven</h1>
    
    <div class="label-container">
        <h5>Name:</h5>
        <p>{{name}}</p>
    
        <h5>Class:</h5>
        <p>{{class}}</p>
    </div>

    <table id="item_table"></table>

    <script>
        async function getItems() {
            return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
        }

        async function refreshItems() {
            document.getElementById("item_table").innerHTML = ""
            const items = await getItems()
            let htmlString = `<tr>
                <th>Name</th>
                <th>Morph</th>
                <th>Price</th>
                <th>Amount</th>
                <th>Description</th>
                <th>Date Added</th>
            </tr>`
            items.forEach((snake) => {
                htmlString += `\n<tr>
                <td>${snake.fields.name}</td>
                <td>${snake.fields.morph}</td>
                <td>${snake.fields.price}</td>
                <td>${snake.fields.amount}</td>
                <td>${snake.fields.description}</td>
                <td>${snake.fields.date_added}</td>
            </tr>` 
            })
            
            document.getElementById("item_table").innerHTML = htmlString

        function addItem() {
            fetch("{% url 'main:add_item_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshItems)

            document.getElementById("form").reset()
            return false
        }

        document.getElementById("button_add").onclick = addItem
        }

        refreshItems()
    </script>
    
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content label-container">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="morph" class="col-form-label">Morph:</label>
                            <input type="text" class="form-control" id="morph" name="morph"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Price:</label>
                            <input type="number" class="form-control" id="price" name="price"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn button-secondary2" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn button-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>
    
    <!-- <table>
        <tr>
            <th>Name</th>
            <th>Morph</th>
            <th>Price</th>
            <th>Amount</th>
            <th>Description</th>
            <th>Date Added</th>
            <th>Edit</th>
        </tr>

        {% for item in items %}
            <tr>
                <td>{{item.name}}</td>
                <td>{{item.morph}}</td>
                <td>{{item.price}}</td>
                <td>{{item.amount}}</td>
                <td>{{item.description}}</td>
                <td>{{item.date_added}}</td>
                <td>
                    <a href="{% url 'main:edit_item' item.pk %}">
                        <button class="button-secondary">
                            Edit
                        </button>
                    </a>
                    <a href="{% url 'main:delete_item' item.pk %}">
                        <button class="button-secondary delete-button">
                            Delete
                        </button>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table> -->
<br />

<button type="button" class="btn button-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>

<a href="{% url 'main:create_item' %}">
    <button class="button-primary">
        Add New Item
    </button>
</a>

<a href="{% url 'main:logout' %}">
    <button class="button-primary">
        Logout
    </button>
</a>

<h6>Sesi terakhir login: {{ last_login }}</h6>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Crimson+Text:wght@700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=family=Open+Sans:wght@400;500;600&display=swap" rel="stylesheet">

<style>
    body {
        background-image: url('https://e1.pxfuel.com/desktop-wallpaper/48/879/desktop-wallpaper-green-python-green-snake-tree-branch-reptile-coiled-snake-animals-green-tree-python.jpg');
        /* background-image: url('https://www.worldatlas.com/upload/a4/91/91/shutterstock-1708408498.jpg'); */
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        font-family: 'Open Sans', sans-serif;
        /* background-color: #060F02; */
    }

    .login {
        text-align: center; /* Center align the content */
        padding: 20px; /* Add padding to center align the content vertically */
    }

    input {
        width: 440px;
        background-color: rgba(255,255,255,0.13);
        border-radius: 10px;
        backdrop-filter: blur(10px);
        border: 2px solid rgba(255,255,255,0.1);
        box-shadow: 0 0 40px rgba(8,7,16,0.6);
        margin: 0 auto; /* Center align the container */
        padding: 16px; /* Add padding to center align the content horizontally */
        margin-top: 32px;
        margin-bottom: 20px;
    }

    th, td, h1, ul, li, p {
        color: #FDFFFB;
    }

    h1 {
        margin-top: 28px;
        text-align: center;
        font-family: 'Crimson Text', serif;
        font-size: 52px;
    }

    p {
        margin-top: 20px;
        margin-bottom: 0;
        font-weight: 500;
    }

    td {
        padding-bottom: 20px;
    }

    .label-container {
        width: 720px;
        background-color: rgba(255,255,255,0.13);
        border-radius: 10px;
        backdrop-filter: blur(10px);
        border: 2px solid rgba(255,255,255,0.1);
        box-shadow: 0 0 40px rgba(8,7,16,0.6);
        margin: 0 auto; /* Center align the container */
        padding: 20px; /* Add padding to center align the content horizontally */
        margin-top: 32px;
        padding-bottom: 40px;
        margin-bottom: 32px;
    }

    .label-container1 {
        width: 440px;
        background-color: rgba(255,255,255,0.13);
        border-radius: 10px;
        backdrop-filter: blur(10px);
        border: 2px solid rgba(255,255,255,0.1);
        box-shadow: 0 0 40px rgba(8,7,16,0.6);
        margin: 0 auto; /* Center align the container */
        padding: 16px; /* Add padding to center align the content horizontally */
        margin-top: 32px;
    }

    .button-primary {
        padding: 16px 40px;
        display: inline-block;
        justify-content: center;
        align-items: center;
        gap: 8px;
        border-radius: 16px;
        border: none;
        background: #54BF21;
        color: #FFF;
        font-size: 16px;
        font-style: normal;
        font-weight: 400;
        line-height: normal;
        margin-top: 28px;
        margin-bottom: 20px;
    }

    .button-secondary {
        padding: 16px 40px;
        display: inline-block;
        justify-content: center;
        align-items: center;
        gap: 8px;
        border-radius: 16px;
        border: none;
        background: #B1E09B;
        color: #060F02;
        font-size: 16px;
        font-style: normal;
        font-weight: 400;
        line-height: normal;
        margin-top: 16px;
    }

    a {
        text-decoration: none;
        margin-bottom: 0px;
    }
</style>

<div class = "login label-container">
    
    <h1>Register</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input class="button-primary" type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
            {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}